### ISSUE TITLE
QT c++11 Flag

### ISSUE THREAD

**Issue by DomtronVox** [Proj-Ascension/Client#43]
Hay so I tried compiling with cmake and aparently ubuntu 14.04's version is "too old". Anyway I fired up qtcreator to build the client and it came back with a number of c++11 related errors. I looked around and according to [this StackOverflow question](http://stackoverflow.com/questions/16948382/how-to-enable-c11-in-qt-creator) the **"CONFIG += c++11"** only works for QT 5. I switched it with **"QMAKE_CXXFLAGS += -std=c++11"** which older QT versions and gcc/clang support. After that everything compiled fine. 

I know this project is in really early development but if it doesn't require QT 5 (I don't see a dependency list) the second form I listed above should be used. I just wanted to point it out and it is fine to just dismiss this if QT5 is a planned requirement.

**Comment by lolzballs** [comment]
We'll be removing support for qmake soon, with solely cmake support. The cmake version is set to 3.1.0 because Windows had issues with lower versions. You can force cmake to run, or use a ppa which contains a higher version such as ppa:george-edison55/cmake-3.x, or ppa:sschuberth/cmake-here.

As well, we will be only supporting Qt 5, with C++11 features, which cmake already has setup.
